### ISSUE TITLE
0.2.0 not on crates.io

### ISSUE THREAD

**Issue by patternseek** [jmagnuson/linemux#34]
Version 0.2.0 isn't present on crates.io.
Thanks!

**Comment by jmagnuson** [comment]
Sorry about that, a bit of an unexpected snafu with crates.io rules for dependency names.

#33 to release 0.2.1 will get merged and published either today or tomorrow.

**Comment by jmagnuson** [comment]
0.2.1 has been published to crates.io: https://crates.io/crates/linemux/0.2.1

Closing
