### ISSUE TITLE
tail files from start

### ISSUE THREAD

**Issue by Alexei-Barnes** [jmagnuson/linemux#46]
My use case for this library includes both the existing behaviour (tailing files from where they are now) as well as tailing fails from the start of the files.

I've implemented a potential approach to this on my fork: https://github.com/Alexei-Barnes/linemux/commit/24644f9ca43bd5f6b659db551ebb17073e92ca7f
And this is open as PR #45 

There are two key elements to this change:
1. Make the size we seek to for the file we are adding `0` when we want to read from start.
2. Store a clone of the `tx` for sending `notify` events for our watched files, and push in an initial event when we start watching a file that we want to read from start.

The first part ensures that we start reading from the start of the file, rather than the end.
The second change allows us to immediately get existing lines from the file, without having to wait for the file to be modified.

**Comment by jmagnuson** [comment]
Completed as part of #58
